# Generated by Django 5.1.15 on 2026-04-30 01:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness_rating', models.PositiveIntegerField(help_text='How clean was this roommate? 1=terrible, 5=spotless', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('noise_rating', models.PositiveIntegerField(help_text='How respectful of noise levels? 1=very loud, 5=very quiet', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.PositiveIntegerField(help_text='Overall experience living with this person.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional written feedback.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='The booking during which they were roommates.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='rooms.booking')),
                ('reviewee', models.ForeignKey(help_text='The roommate being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='The student who is leaving the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'reviewee', 'booking'), name='one_feedback_per_roommate_per_booking')],
            },
        ),
    ]
